# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-25 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_username', models.TextField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age_range', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('education', models.TextField(null=True)),
                ('political', models.TextField(null=True)),
                ('political_engage', models.TextField(null=True)),
                ('moral0', models.IntegerField(default=0)),
                ('moral1', models.IntegerField(default=0)),
                ('moral2', models.IntegerField(default=0)),
                ('moral3', models.IntegerField(default=0)),
                ('moral4', models.IntegerField(default=0)),
                ('moral5', models.IntegerField(default=0)),
                ('control0', models.IntegerField(default=0)),
                ('control1', models.IntegerField(default=0)),
                ('control2', models.IntegerField(default=0)),
                ('control3', models.IntegerField(default=0)),
                ('control4', models.IntegerField(default=0)),
                ('control5', models.IntegerField(default=0)),
                ('scaleable_vote', models.FloatField(default=0.0)),
                ('scaleable_action_content', models.TextField(null=True)),
                ('scaleable_action_user', models.TextField(null=True)),
                ('scaleable0', models.IntegerField(default=0)),
                ('scaleable1', models.IntegerField(default=0)),
                ('scaleable2', models.IntegerField(default=0)),
                ('scaleable3', models.IntegerField(default=0)),
                ('scaleable4', models.IntegerField(default=0)),
                ('scaleable5', models.IntegerField(default=0)),
                ('immersive_vote', models.FloatField(default=0.0)),
                ('immersive_action_content', models.TextField(null=True)),
                ('immersive_action_user', models.TextField(null=True)),
                ('immersive0', models.IntegerField(default=0)),
                ('immersive1', models.IntegerField(default=0)),
                ('immersive2', models.IntegerField(default=0)),
                ('immersive3', models.IntegerField(default=0)),
                ('immersive4', models.IntegerField(default=0)),
                ('immersive5', models.IntegerField(default=0)),
                ('complete0', models.TextField(null=True)),
                ('complete1', models.TextField(null=True)),
                ('complete2', models.TextField(null=True)),
                ('complete3', models.TextField(null=True)),
                ('complete4', models.TextField(null=True)),
                ('complete5', models.TextField(null=True)),
                ('complete6', models.TextField(null=True)),
                ('complete7', models.TextField(null=True)),
                ('complete8', models.TextField(null=True)),
                ('complete9', models.TextField(null=True)),
                ('complete10', models.TextField(null=True)),
                ('complete11', models.TextField(null=True)),
                ('groupinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juries.GroupInfo')),
                ('mturk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juries.GroupInfo'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juries.UserInfo'),
        ),
    ]
