# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='scaleable_explanation',
            field=models.TextField(null=True),
        ),
    ]
