# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0003_auto_20190325_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='scaleable_vote',
            field=models.FloatField(default=None, null=True),
        ),
    ]
