# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-26 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0004_auto_20190325_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat_username',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='chat_username',
            field=models.TextField(null=True),
        ),
    ]
