# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-26 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0005_auto_20190326_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='immersive_action_content',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='immersive_action_user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_content_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_content_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_content_unlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_user_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_user_permaban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_user_warn',
            field=models.BooleanField(default=False),
        ),
    ]
