# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-26 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0006_auto_20190326_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='immersive_vote',
            field=models.FloatField(default=None, null=True),
        ),
    ]
