# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-29 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0008_userinfo_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='control_difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='control_satisfaction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='control_time',
            field=models.IntegerField(default=0),
        ),
    ]
