# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-29 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0009_auto_20190329_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='scaleable_difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='scaleable_justification',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='scaleable_satisfaction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='scaleable_time',
            field=models.IntegerField(default=0),
        ),
    ]
