# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-29 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0010_auto_20190329_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='scaleable_explanation',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_convo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_justification',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_satisfaction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='immersive_trust',
            field=models.IntegerField(default=0),
        ),
    ]
