# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-29 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juries', '0014_auto_20190329_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='complete_nonpref',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='complete_pref',
            field=models.TextField(null=True),
        ),
    ]
